steps:
  # Step 1: Verify Data Residency Compliance for Cloud SQL
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['sql', 'instances', 'describe', 'europe-sql-db', '--format=json']
    id: 'verify-sql-instance'
    waitFor: ["-"]

  # Step 2: Verify Other Resources if Necessary
  # You can add additional steps here to check other resources or configurations
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['compute', 'instances', 'list', '--filter=location:europe-west1']

options:
  logging: CLOUD_LOGGING_ONLY

